### ISSUE TITLE
Remove raw pointer usage [TRACKER]

### ISSUE THREAD

**Issue by henriquegemignani** [uspgamedev/ugdk#38]
Use smart pointers to automate memory management and document clearly when a function steals ownership.
- [x] Scenes @ system::PushScene
- [ ] CollisionObjects @ CollisionManager

Certainly more...

EDIT (by @Kazuo256):

Track of raw pointers-related issues:

+ [x] action::SpriteAnimationTable #63
+ [x] action::Observer  #64
+ [x] audio::Sample and audio::Music #67
+ [x] MediaManager at action::MediaPlayer::ChangeMediaManager #71 
+ [x] action::MediaPlayer #73
+ [x] audio::Manager #74
+ [x] desktop::Manager #76
+ [x] filesystem::Manager #82
+ [x] input::Manager #83
+ [x] resource::Manager #84
+ [x] time::Manager #85
+ [x] graphic::Manager #93
+ [x] text::Manager #94 
+ [x] system::IListener #98 

Raw pointers that will not be removed:

+ `T*` in `structure::IndexableTable`
+ `T*` in `resource::ResourceContainer`

**Comment by RudaF** [comment]
Another files that use raw pointers for further change

modules\ugdk-2d\include\ugdk\desktop\2D\window.h 
modules\ugdk-2d\include\ugdk\desktop\graphic\canvas.h 
modules\ugdk-2d\include\ugdk\desktop\graphic\defaultshaders.h
modules\ugdk-2d\include\ugdk\desktop\graphic\exceptions.h
modules\ugdk-2d\include\ugdk\desktop\graphic\immediate.h
modules\ugdk-2d\include\ugdk\desktop\graphic\manager.h
modules\ugdk-2d\include\ugdk\desktop\graphic\module.h
modules\ugdk-2d\include\ugdk\desktop\graphic\primitive.h
modules\ugdk-2d\include\ugdk\desktop\graphic\primitivecontroller.h
modules\ugdk-2d\include\ugdk\desktop\graphic\primitivesetup.h
modules\ugdk-2d\include\ugdk\desktop\graphic\rendertexture.h
modules\ugdk-2d\include\ugdk\desktop\graphic\sprite.h
modules\ugdk-2d\include\ugdk\desktop\graphic\textureatlas.h
modules\ugdk-2d\include\ugdk\desktop\graphic\testureunit.h
modules\ugdk-2d\include\ugdk\desktop\graphic\vertexdata.h
modules\ugdk-2d\include\ugdk\desktop\text\font.h
modules\ugdk-2d\include\ugdk\desktop\text\functions.h
modules\ugdk-2d\include\ugdk\desktop\text\label.h
modules\ugdk-2d\include\ugdk\desktop\text\manager.h
modules\ugdk-2d\include\ugdk\desktop\text\module.h
modules\ugdk-2d\include\ugdk\desktop\text\textbox.h
modules\ugdk-2d\include\ugdk\desktop\ui\drawable\texturedrectangle.h
modules\ugdk-2d\include\ugdk\desktop\ui\button.h
modules\ugdk-2d\include\ugdk\desktop\ui\drawable.h
modules\ugdk-2d\include\ugdk\desktop\ui\menu.h
modules\ugdk-2d\include\ugdk\desktop\ui\node.h

**Comment by josealvim** [comment]
[raw-pointer(core).txt](https://github.com/uspgamedev/ugdk/files/1026693/raw-pointer.core.txt)

**Comment by josealvim** [comment]
in modules/ugdk-core
    include/
        pyramidworks/
            collision
            collision/
                collisionclass
                collisionmanager
                collisionobject
            geometry/
                circle
                convexpolygon
                geometricshape
                rect
        ugdk/
            action/
                animationplayer
                events
                json2spriteanimation
                mediamanager
                mediaplayer
                scene
            audio/
                manager
                module
            debug/
                log
            desktop/
                module
                window
            filesystem/
                file
                manager
                module
            input/
                events
                joystick
                keyboard
                manager
                module
                mouse
                textinput
            resource/
                manager
                module
                resourceconainer
            structure/
                box
                indexabletable
                intervalkdtree
            system/
                engine
                eventhandler
                exceptions
            time/
                module
            util/
                utf8

**Comment by Kazuo256** [comment]
We'll probably have to split this issue into many.

**Comment by josealvim** [comment]
In modules
In ugdk-core
presume all in namespace ugdk

+ [ ] pyramidworks::`collision`::CollisionObject at:
  + pyramidworks::`collision`::CollisionManager::AddActiveObject
  + pyramidworks::`collision`::CollisionManager::RemoveActiveObject
  + pyramidworks::`collision`::CollisionManager::active_objects
+ [ ] Scene at:
  + [x] system::PushScene
  + action::SceneFocusEvent::SceneFocusEvent
  + action::SceneDeFocusEvent::SceneDeFocusEvent
  + action::SceneFinishedEvent::SceneFinishedEvent


+ [ ] char* at
  + debug::ConvertLogToString
  + filesystem::Manager::OpenFile
  + input::TextInputEvent::TextInputEvent
  + filesystem::File::fgets
  + input::TextInput::current_composition
  + system::BaseException::BaseException
  + system::BaseException::what
  + system::BaseException::InvalidOperation::InvalidOperation
  + util/utf8.h @ utf8_to_ucs4
  + util/utf8.h @ ucs4_to_utf8

+ [ ] void* at
  + filesystem::File::ReadRaw
  + filesystem::File::WriteRaw






+ [ ] class T* at
  + filesystem::File::Read
  + filesystem::File::Write

+ [ ] resource::ResourceContainer at
  + resource::ResourceContainer::Get
  + resource::Manager::GetContainer

+ [ ] structure::Box at
  + structure::Box::Intersects

+ [ ] structure::ikdtree::Item at
  + structure::ikdtree::IntervalKDTree::begin
  + structure::ikdtree::IntervalKDTree::end
  + structure::ikdtree::Node::InsertItem
  + structure::ikdtree::Node::RemoveItem
  + structure::ikdtree::UpdateItem


+ [ ] structure::ikdtree::Node at
  + structure::ikdtree::Item::set_container_node
  + structure::ikdtree::Item::container_node
  + structure::ikdtree::Node::Node

+ [ ] structure::ikdtree::IntervalKDTree at
  + structure::ikdtree::Node::Node

+ [ ] system::SDLEventHandler at
  + system::RegisterSDLHandler
  + system::DeregisterSDLHandler

**Comment by rubens-bolgheroni** [comment]
+ [ ] RenderTarget at:
  + graphic::Canvas::Canvas
+ [ ] ShaderProgram at:
  + graphic::ShaderProgram
+ [ ] char at:
   + desktop::mode2d::Window
  + graphic::NotSupportedException
  + graphic::VertexData::Checksizes
+ [ ] GLTexture at:
  + graphic::immediate::Rectangle
  + graphic::Primitive::Primitive
  + graphic::PrimitiveSetup::Rectangle::Prepare
  + graphic::RenderTexture::RenderTarget
  + graphic::TextureAtlas::TextureAtlas
  + graphic::TextureUnit::BindTexture
  + ui::TexturedRectangle
+ [ ]  TextureAtlas at:
  + graphic::immediate::Rectangle
  + graphic::PrimitiveSetup::Sprite::Prepare
  + graphic::PrimitiveControllerSprite::PrimitiveControllerSprite
  + graphic::TextureAtlas::BoundPiece
+ [ ] void at:
  +??????manager.h
+ [ ] ShaderProgram at:
  + graphic::Primitive::Primitive
+ [ ] Primitive at:
  + graphic::PrimitiveController::set_owner
+ [ ] T at:
  + graphic::VertexData::Mapper<class T>
+ [ ] texture_font_t at:
  + text::Font
+ [ ] Font at:
  + text::FillBufferWithText
  + text::DrawTextLine
  + text::Label::Label
  + text::Manager
+ [ ] TextBox at:
  + text::Manager
  + text::TextBox::TextBox
+ [ ] Button at:
  + ui
+ [ ] Drawable at:
  + ui::Drawable::set_draw_setup_function
  + ui::Node
+  [ ] menu pointer at:
   + ui::MenuCallback
+ [ ] UIElement pointer at:
  + ui::Menu
+ [ ] Node at:
  + ui::Menu
  + ui::Node
